// Processors are generated by domaingen, DO NOT EDIT
{{template "proc.usage.creator" . }}
{{template "proc.usage.updater" . }}
{{template "proc.usage.upserter" . }}
{{template "proc.usage.reader" . }}
{{template "proc.usage.search" . }}
{{template "proc.usage.one_rel_processor" . }}
{{template "proc.usage.rels_processor" . }}
{{template "proc.usage.rels_lister" . }}
package {{pkgName .ProcessorPkg}}

import (
  "inventory_service/domain"
  "database/sql"
  ctx "inventory_service/context"
	"inventory_service/errors"
)

